/// Model class for the `one_time_pins` table.
///
/// OTPs are generated by the owner and given to staff to authorize
/// manual transaction entries in strict security mode.
/// Each OTP expires after [AppConstants.otpExpiryMinutes] minutes.
class OneTimePinModel {
  final int? id;
  final int storeId;
  final int staffId;
  final String pinHash; // SHA-256 hashed — never raw
  final String purpose; // 'manual_entry'
  final int isUsed; // 1 = already consumed
  final String expiresAt; // DB datetime string
  final String createdAt;
  final String syncId;

  const OneTimePinModel({
    this.id,
    required this.storeId,
    required this.staffId,
    required this.pinHash,
    required this.purpose,
    this.isUsed = 0,
    required this.expiresAt,
    required this.createdAt,
    required this.syncId,
  });

  factory OneTimePinModel.fromMap(Map<String, dynamic> map) => OneTimePinModel(
        id: map['id'] as int?,
        storeId: map['store_id'] as int,
        staffId: map['staff_id'] as int,
        pinHash: map['pin_hash'] as String,
        purpose: map['purpose'] as String,
        isUsed: map['is_used'] as int? ?? 0,
        expiresAt: map['expires_at'] as String,
        createdAt: map['created_at'] as String,
        syncId: map['sync_id'] as String,
      );

  Map<String, dynamic> toMap() => {
        if (id != null) 'id': id,
        'store_id': storeId,
        'staff_id': staffId,
        'pin_hash': pinHash,
        'purpose': purpose,
        'is_used': isUsed,
        'expires_at': expiresAt,
        'created_at': createdAt,
        'sync_id': syncId,
      };

  OneTimePinModel copyWith({
    int? id,
    int? storeId,
    int? staffId,
    String? pinHash,
    String? purpose,
    int? isUsed,
    String? expiresAt,
    String? createdAt,
    String? syncId,
  }) =>
      OneTimePinModel(
        id: id ?? this.id,
        storeId: storeId ?? this.storeId,
        staffId: staffId ?? this.staffId,
        pinHash: pinHash ?? this.pinHash,
        purpose: purpose ?? this.purpose,
        isUsed: isUsed ?? this.isUsed,
        expiresAt: expiresAt ?? this.expiresAt,
        createdAt: createdAt ?? this.createdAt,
        syncId: syncId ?? this.syncId,
      );

  bool get used => isUsed == 1;

  @override
  String toString() =>
      'OneTimePinModel(id: $id, staffId: $staffId, isUsed: $isUsed)';
}
